const { v4: uuidv4 } = require("uuid");
const bcrypt = require("bcryptjs");

("use strict");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const hash = await bcrypt.hash("Uu123456", 10);
    const usersArray = [
      {
        firstName: "John",
        lastName: "Doe",
        birthday: "1990-01-01",
        email: "john.doe@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Jane",
        lastName: "Smith",
        birthday: "1985-05-15",
        email: "jane.smith@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Bob",
        lastName: "Johnson",
        birthday: "1978-11-20",
        email: "bob.johnson@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Emily",
        lastName: "Brown",
        birthday: "1995-03-02",
        email: "emily.brown@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "David",
        lastName: "Lee",
        birthday: "1980-07-10",
        email: "david.lee@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Alice",
        lastName: "Jones",
        birthday: "1992-04-15",
        email: "alice.jones@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Benjamin",
        lastName: "Nguyen",
        birthday: "1987-09-27",
        email: "benjamin.nguyen@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Carla",
        lastName: "Garcia",
        birthday: "1985-06-11",
        email: "carla.garcia@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "David",
        lastName: "Williams",
        birthday: "1979-01-23",
        email: "david.williams@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Elena",
        lastName: "Hernandez",
        birthday: "1983-12-06",
        email: "elena.hernandez@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Frank",
        lastName: "Davis",
        birthday: "1990-02-14",
        email: "frank.davis@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Gabriela",
        lastName: "Martinez",
        birthday: "1976-07-29",
        email: "gabriela.martinez@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Henry",
        lastName: "Jackson",
        birthday: "1982-03-08",
        email: "henry.jackson@example.com",
        password: hash,
        phoneNumber: "12345678",
        role: "patient",
        uuid: uuidv4(),
      },
      {
        firstName: "Walid",
        lastName: "Abou Karam",
        birthday: "1982-03-08",
        email: "dr@gmail.com",
        password: hash,
        phoneNumber: "12345678",
        role: "doctor",
        uuid: uuidv4(),
      },
      {
        firstName: "Pharmacy",
        lastName: "Elie",
        birthday: "1982-03-08",
        email: "pharmelie@gmail.com",
        password: hash,
        phoneNumber: "12345678",
        role: "pharmacy",
        uuid: uuidv4(),
      },
      {
        firstName: "Pharmacy",
        lastName: "Joe",
        birthday: "1982-03-08",
        email: "pharmJoe@gmail.com",
        password: hash,
        phoneNumber: "12345678",
        role: "pharmacy",
        uuid: uuidv4(),
      },
      {
        firstName: "Pharmacy",
        lastName: "Rita",
        birthday: "1982-03-08",
        email: "pharmRita@gmail.com",
        password: hash,
        phoneNumber: "12345678",
        role: "pharmacy",
        uuid: uuidv4(),
      },
    ];
    const appointmentsArray = [
      {
        patientId: 1,
        date: "2023-05-02",
        time: "14:30:00",
        description: "Checkup for flu symptoms",
        patientUUID: usersArray[0].uuid,
      },
      {
        patientId: 2,
        date: "2023-05-03",
        time: "10:00:00",
        description: "Physical exam",
        patientUUID: usersArray[1].uuid,
      },
      {
        patientId: 3,
        date: "2023-05-04",
        time: "15:45:00",
        description: "Follow up appointment",
        patientUUID: usersArray[2].uuid,
      },
      {
        patientId: 4,
        date: "2023-05-05",
        time: "09:30:00",
        description: "Consultation for back pain",
        patientUUID: usersArray[3].uuid,
      },
      {
        patientId: 5,
        date: "2023-05-06",
        time: "11:15:00",
        description: "Dental cleaning",
        patientUUID: usersArray[4].uuid,
      },
      {
        patientId: 6,
        date: "2023-05-07",
        time: "13:00:00",
        description: "Eye exam",
        patientUUID: usersArray[5].uuid,
      },
      {
        patientId: 7,
        date: "2023-05-08",
        time: "16:30:00",
        description: "Checkup for allergies",
        patientUUID: usersArray[6].uuid,
      },
      {
        patientId: 8,
        date: "2023-05-09",
        time: "11:00:00",
        description: "Physical therapy session",
        patientUUID: usersArray[7].uuid,
      },
      {
        patientId: 9,
        date: "2023-05-10",
        time: "15:15:00",
        description: "Follow up appointment",
        patientUUID: usersArray[8].uuid,
      },
      {
        patientId: 10,
        date: "2023-05-11",
        time: "10:30:00",
        description: "Consultation for sinus infection",
        patientUUID: usersArray[9].uuid,
      },
      {
        patientId: 11,
        date: "2023-04-30",
        time: "11:00:00",
        description: "Blood test",
        patientUUID: usersArray[10].uuid,
      },
      {
        patientId: 12,
        date: "2023-05-01",
        time: "12:30:00",
        description: "Annual physical exam",
        patientUUID: usersArray[11].uuid,
      },
      {
        patientId: 13,
        date: "2023-05-01",
        time: "14:15:00",
        description: "Follow up appointment",
        patientUUID: usersArray[1].uuid,
      },
      {
        patientId: 4,
        date: "2023-05-02",
        time: "16:00:00",
        description: "Consultation for shoulder pain",
        patientUUID: usersArray[3].uuid,
      },
      {
        patientId: 5,
        date: "2023-05-03",
        time: "11:45:00",
        description: "Dental checkup",
        patientUUID: usersArray[4].uuid,
      },
      {
        patientId: 6,
        date: "2023-05-03",
        time: "13:30:00",
        description: "Eye exam",
        patientUUID: usersArray[5].uuid,
      },
      {
        patientId: 7,
        date: "2023-05-04",
        time: "15:30:00",
        description: "Checkup for asthma",
        patientUUID: usersArray[6].uuid,
      },
      {
        patientId: 8,
        date: "2023-05-05",
        time: "09:30:00",
        description: "Physical therapy session",
        patientUUID: usersArray[7].uuid,
      },
      {
        patientId: 9,
        date: "2023-05-06",
        time: "16:00:00",
        description: "Follow up appointment",
        patientUUID: usersArray[8].uuid,
      },
      {
        patientId: 10,
        date: "2023-05-07",
        time: "10:30:00",
        description: "Consultation for migraine headaches",
        patientUUID: usersArray[9].uuid,
      },
    ];
    const patientConditions = [
      {
        patientId: 1,
        description: "Has a history of asthma",
        isCurrent: true,
        patientUUID: usersArray[0].uuid,
      },
      {
        patientId: 1,
        description: "Was diagnosed with diabetes last year",
        isCurrent: true,
        patientUUID: usersArray[0].uuid,
      },
      {
        patientId: 2,
        description: "Has high blood pressure and takes medication for it",
        isCurrent: true,
        patientUUID: usersArray[1].uuid,
      },
      {
        patientId: 2,
        description: "Has arthritis in both knees",
        isCurrent: false,
        patientUUID: usersArray[10].uuid,
      },
      {
        patientId: 3,
        description:
          "Has been diagnosed with depression and is currently seeing a therapist",
        isCurrent: true,
        patientUUID: usersArray[2].uuid,
      },
      {
        patientId: 3,
        description: "Has occasional migraines and takes medication for them",
        isCurrent: false,
        patientUUID: usersArray[11].uuid,
      },
      {
        patientId: 4,
        description: "Has epilepsy and takes medication to control seizures",
        isCurrent: true,
        patientUUID: usersArray[3].uuid,
      },
      {
        patientId: 5,
        description: "Has allergies to pollen and dust",
        isCurrent: true,
        patientUUID: usersArray[4].uuid,
      },

      {
        patientId: 6,
        description: "Was diagnosed with type 2 diabetes two years ago",
        isCurrent: true,
        patientUUID: usersArray[5].uuid,
      },

      {
        patientId: 7,
        description: "Has high blood pressure and takes medication for it",
        isCurrent: true,
        patientUUID: usersArray[6].uuid,
      },

      {
        patientId: 8,
        description: "Has rheumatoid arthritis and takes medication for it",
        isCurrent: true,
        patientUUID: usersArray[7].uuid,
      },

      {
        patientId: 9,
        description: "Has been diagnosed with bipolar disorder",
        isCurrent: true,
        patientUUID: usersArray[8].uuid,
      },

      {
        patientId: 10,
        description: "Has chronic migraines and takes medication for them",
        isCurrent: true,
        patientUUID: usersArray[9].uuid,
      },
      {
        patientId: 11,
        description: "Has a history of depression and anxiety",
        isCurrent: false,
        patientUUID: usersArray[1].uuid,
      },

      {
        patientId: 12,
        description: "Has a heart condition and takes medication for it",
        isCurrent: false,
        patientUUID: usersArray[2].uuid,
      },

      {
        patientId: 13,
        description: "Has asthma and uses an inhaler",
        isCurrent: false,
        patientUUID: usersArray[3].uuid,
      },

      {
        patientId: 14,
        description:
          "Has a history of migraines and has tried multiple treatments",
        isCurrent: false,
        patientUUID: usersArray[4].uuid,
      },
      {
        patientId: 15,
        description: "Has chronic back pain and undergoes physical therapy",
        isCurrent: false,
        patientUUID: usersArray[5].uuid,
      },
      {
        patientId: 16,
        description:
          "Has a gluten allergy and follows a strict gluten-free diet",
        isCurrent: false,
        patientUUID: usersArray[6].uuid,
      },
    ];
    const medicines = [
      {
        medicine: "Ibuprofen",
        isCurrent: true,
        description: "Pain reliever",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 19,
        patientUUID: usersArray[0].uuid,
      },

      {
        medicine: "Lisinopril",
        isCurrent: true,
        description: "Blood pressure medication",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 20,
        patientUUID: usersArray[0].uuid,
      },

      {
        medicine: "Prednisone",
        isCurrent: true,
        description: "Corticosteroid",
        frequency: 3,
        foodTiming: "before",
        prescriptionId: 21,
        patientUUID: usersArray[0].uuid,
      },

      {
        medicine: "Albuterol",
        isCurrent: false,
        description: "Bronchodilator",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 22,
        patientUUID: usersArray[0].uuid,
      },

      {
        medicine: "Escitalopram",
        isCurrent: false,
        description: "Antidepressant",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 23,
        patientUUID: usersArray[0].uuid,
      },

      {
        medicine: "Hydrocodone",
        isCurrent: false,
        description: "Narcotic pain reliever",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 24,
        patientUUID: usersArray[0].uuid,
      },
      {
        medicine: "Metformin",
        isCurrent: true,
        description: "Oral diabetes medication",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 25,
        patientUUID: usersArray[1].uuid,
      },

      {
        medicine: "Levothyroxine",
        isCurrent: true,
        description: "Thyroid hormone replacement",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 26,
        patientUUID: usersArray[1].uuid,
      },

      {
        medicine: "Simvastatin",
        isCurrent: true,
        description: "Cholesterol-lowering medication",
        frequency: 3,
        foodTiming: "after",
        prescriptionId: 27,
        patientUUID: usersArray[1].uuid,
      },

      {
        medicine: "Aspirin",
        isCurrent: false,
        description: "Blood thinner",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 28,
        patientUUID: usersArray[1].uuid,
      },

      {
        medicine: "Losartan",
        isCurrent: true,
        description: "Blood pressure medication",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 29,
        patientUUID: usersArray[2].uuid,
      },

      {
        medicine: "Atorvastatin",
        isCurrent: true,
        description: "Cholesterol-lowering medication",
        frequency: 3,
        foodTiming: "after",
        prescriptionId: 30,
        patientUUID: usersArray[2].uuid,
      },

      {
        medicine: "Omeprazole",
        isCurrent: true,
        description: "Proton pump inhibitor",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 31,
        patientUUID: usersArray[2].uuid,
      },

      {
        medicine: "Sertraline",
        isCurrent: false,
        description: "Antidepressant",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 32,
        patientUUID: usersArray[2].uuid,
      },

      {
        medicine: "Metoprolol",
        isCurrent: false,
        description: "Beta blocker",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 33,
        patientUUID: usersArray[2].uuid,
      },
      {
        medicine: "Lisinopril",
        isCurrent: true,
        description: "Blood pressure medication",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 34,
        patientUUID: usersArray[3].uuid,
      },

      {
        medicine: "Metoprolol",
        isCurrent: true,
        description: "Beta blocker",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 35,
        patientUUID: usersArray[3].uuid,
      },

      {
        medicine: "Citalopram",
        isCurrent: false,
        description: "Antidepressant",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 36,
        patientUUID: usersArray[3].uuid,
      },

      {
        medicine: "Escitalopram",
        isCurrent: false,
        description: "Antidepressant",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 37,
        patientUUID: usersArray[3].uuid,
      },

      {
        medicine: "Furosemide",
        isCurrent: true,
        description: "Diuretic",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 38,
        patientUUID: usersArray[4].uuid,
      },

      {
        medicine: "Warfarin",
        isCurrent: true,
        description: "Blood thinner",
        frequency: 3,
        foodTiming: "before",
        prescriptionId: 39,
        patientUUID: usersArray[4].uuid,
      },

      {
        medicine: "Ramipril",
        isCurrent: true,
        description: "Blood pressure medication",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 40,
        patientUUID: usersArray[4].uuid,
      },

      {
        medicine: "Atenolol",
        isCurrent: false,
        description: "Beta blocker",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 41,
        patientUUID: usersArray[4].uuid,
      },

      {
        medicine: "Fluoxetine",
        isCurrent: true,
        description: "Antidepressant",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 42,
        patientUUID: usersArray[5].uuid,
      },
      {
        medicine: "Zyrtec",
        isCurrent: true,
        description: "Allergy medication",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 43,
        patientUUID: usersArray[5].uuid,
      },
      {
        medicine: "Benadryl",
        isCurrent: true,
        description: "Allergy medication",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 44,
        patientUUID: usersArray[5].uuid,
      },
      {
        medicine: "Allegra",
        isCurrent: true,
        description: "Allergy medication",
        frequency: 2,
        foodTiming: "after",
        prescriptionId: 45,
        patientUUID: usersArray[5].uuid,
      },
      {
        medicine: "Claritin",
        isCurrent: false,
        description: "Allergy medication",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 46,
        patientUUID: usersArray[5].uuid,
      },
      {
        medicine: "Flonase",
        isCurrent: false,
        description: "Allergy medication",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 47,
        patientUUID: usersArray[5].uuid,
      },

      {
        medicine: "Hydroxyzine",
        isCurrent: true,
        description: "Antihistamine",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 48,
        patientUUID: usersArray[6].uuid,
      },
      {
        medicine: "Doxepin",
        isCurrent: true,
        description: "Antidepressant",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 49,
        patientUUID: usersArray[6].uuid,
      },
      {
        medicine: "Prozac",
        isCurrent: false,
        description: "Antidepressant",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 50,
        patientUUID: usersArray[6].uuid,
      },
      {
        medicine: "Wellbutrin",
        isCurrent: false,
        description: "Antidepressant",
        frequency: 2,
        foodTiming: "before",
        prescriptionId: 51,
        patientUUID: usersArray[6].uuid,
      },
      {
        medicine: "Zoloft",
        isCurrent: false,
        description: "Antidepressant",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 52,
        patientUUID: usersArray[6].uuid,
      },

      {
        medicine: "Tylenol",
        isCurrent: false,
        description: "Pain reliever",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 53,
        patientUUID: usersArray[7].uuid,
      },
      {
        medicine: "Ibuprofen",
        isCurrent: true,
        description: "Pain reliever",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 54,
        patientUUID: usersArray[7].uuid,
      },
      {
        medicine: "Aspirin",
        isCurrent: true,
        description: "Blood thinner and pain reliever",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 55,
        patientUUID: usersArray[7].uuid,
      },
      {
        medicine: "Naproxen",
        isCurrent: false,
        description: "Pain reliever",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 56,
        patientUUID: usersArray[7].uuid,
      },
      {
        medicine: "Lisinopril",
        isCurrent: true,
        description: "10mg once daily for hypertension",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 12,
        patientUUID: usersArray[8].uuid,
      },
      {
        medicine: "Atorvastatin",
        isCurrent: true,
        description: "20mg once daily for high cholesterol",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 13,
        patientUUID: usersArray[8].uuid,
      },
      {
        medicine: "Metformin",
        isCurrent: true,
        description: "1000mg twice daily for type 2 diabetes",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 14,
        patientUUID: usersArray[8].uuid,
      },
      {
        medicine: "Aspirin",
        isCurrent: true,
        description: "81mg once daily for cardiovascular health",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 15,
        patientUUID: usersArray[8].uuid,
      },
      {
        medicine: "Zyrtec",
        isCurrent: true,
        description: "10mg once daily for allergies",
        frequency: 2,
        foodTiming: "after",
        prescriptionId: 16,
        patientUUID: usersArray[8].uuid,
      },
      {
        medicine: "Albuterol",
        isCurrent: true,
        description: "2 puffs as needed for asthma",
        frequency: 3,
        foodTiming: "N/A",
        prescriptionId: 17,
        patientUUID: usersArray[9].uuid,
      },
      {
        medicine: "Hydrochlorothiazide",
        isCurrent: true,
        description: "25mg once daily for hypertension",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 18,
        patientUUID: usersArray[9].uuid,
      },
      {
        medicine: "Fluticasone",
        isCurrent: true,
        description: "2 sprays once daily for allergies",
        frequency: 1,
        foodTiming: "N/A",
        prescriptionId: 19,
        patientUUID: usersArray[10].uuid,
      },
      {
        medicine: "Propranolol",
        isCurrent: true,
        description: "10mg once daily for anxiety",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 20,
        patientUUID: usersArray[10].uuid,
      },
      {
        medicine: "Ibuprofen",
        isCurrent: true,
        description: "800mg as needed for pain",
        frequency: 3,
        foodTiming: "after",
        prescriptionId: 21,
        patientUUID: usersArray[11].uuid,
      },
      {
        medicine: "Meloxicam",
        isCurrent: true,
        description: "7.5mg once daily for arthritis pain",
        frequency: 1,
        foodTiming: "after",
        prescriptionId: 22,
        patientUUID: usersArray[12].uuid,
      },
      {
        medicine: "Nexium",
        isCurrent: true,
        description: "40mg once daily for GERD",
        frequency: 1,
        foodTiming: "before",
        prescriptionId: 23,
        patientUUID: usersArray[12].uuid,
      },
    ];
    const questions = [
      {
        patientId: 1,
        question: "What are the potential side effects of this medication?",
        answer:
          "Common side effects include nausea and dizziness. If you experience any severe or unusual symptoms, please contact our office immediately.",
        isAnswered: true,
        patientUUID: usersArray[0].uuid,
      },
      {
        patientId: 1,
        question:
          "Is it safe to take this medication with my current health conditions?",
        answer:
          "Based on your medical history, this medication should not interact negatively with your current health conditions.",
        isAnswered: true,
        patientUUID: usersArray[1].uuid,
      },
      {
        patientId: 2,
        question: "What is the best treatment for my condition?",
        answer:
          "Based on your symptoms and medical history, we recommend a combination of medication and physical therapy. Please follow the treatment plan outlined in your medical records and contact our office if you experience any issues.",
        isAnswered: true,
        patientUUID: usersArray[2].uuid,
      },
      {
        patientId: 2,
        question: "What should I do if I miss a dose of my medication?",
        answer:
          "If you miss a dose, take it as soon as you remember. If it is almost time for your next dose, skip the missed dose and continue with your regular dosing schedule. Do not take extra medication to make up for the missed dose.",
        isAnswered: true,
        patientUUID: usersArray[3].uuid,
      },
      {
        patientId: 3,
        question: "How long will it take for my symptoms to improve?",
        answer:
          "The duration of treatment varies depending on the severity of your symptoms and how well you respond to treatment. Typically, patients start to see improvement within a few days to a week.",
        isAnswered: true,
        patientUUID: usersArray[4].uuid,
      },
      {
        patientId: 3,
        question:
          "Are there any alternative treatments to the medication you prescribed?",
        answer:
          "There are alternative treatments available, but based on your medical history and current symptoms, we believe that this medication is the most effective option. If you are interested in exploring alternative treatments, please let us know and we can discuss your options.",
        isAnswered: true,
        patientUUID: usersArray[5].uuid,
      },
      {
        patientId: 4,
        question:
          "What should I do if I experience side effects from the medication?",
        answer:
          "If you experience any side effects, please stop taking the medication and contact our office immediately. We will evaluate your symptoms and determine the best course of action.",
        isAnswered: true,
        patientUUID: usersArray[6].uuid,
      },
      {
        patientId: 4,
        question: "How frequently should I schedule follow-up appointments?",
        answer:
          "The frequency of follow-up appointments depends on the nature and severity of your condition. In general, we recommend scheduling appointments every 3-6 months to monitor your symptoms and adjust your treatment plan if necessary.",
        isAnswered: true,
        patientUUID: usersArray[7].uuid,
      },
      {
        patientId: 5,
        question: "How long should I take this medication?",
        isAnswered: false,
        patientUUID: usersArray[8].uuid,
      },
      {
        patientId: 5,
        answer: "",
        question:
          "Are there any potential interactions with other medications I'm taking?",
        isAnswered: false,
        patientUUID: usersArray[9].uuid,
      },
      {
        patientId: 6,
        answer: "",
        question:
          "What lifestyle changes should I make to improve my condition?",
        isAnswered: false,
        patientUUID: usersArray[10].uuid,
      },
      {
        answer: "",
        patientId: 6,
        question: "How can I manage the side effects of this medication?",
        isAnswered: false,
        patientUUID: usersArray[11].uuid,
      },
      {
        answer: "",
        patientId: 7,
        question:
          "Can you explain the potential risks and benefits of this treatment?",
        isAnswered: false,
        patientUUID: usersArray[12].uuid,
      },
      {
        answer: "",
        patientId: 7,
        question: "Are there any non-pharmacological treatments I can try?",
        isAnswered: false,
        patientUUID: usersArray[1].uuid,
      },
    ];
    await queryInterface.bulkInsert("users", usersArray, {});
    await queryInterface.bulkInsert("appointments", appointmentsArray, {});
    await queryInterface.bulkInsert(
      "medical_conditions",
      patientConditions,
      {}
    );
    await queryInterface.bulkInsert("patient_questions", questions, {});
    await queryInterface.bulkInsert("medicines", medicines, {});
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("users", null, {});
  },
};
